### ISSUE TITLE
Can reach urls.

### ISSUE THREAD

**Issue by slinkyone** [mifi/instauto#112]
Hello!

Since yday night my bot can reaches profile urls. Cant even start because its not seeing my profile url. I copied the url from console and it works in a browser tab, but not in the bot emulated windows. Cannot find “xy user” on page.
Tried to delete cache and all cookies.

Does anybody have some idea? Thanks. :)

**Comment by mifi** [comment]
hi. i'm not sure what you mean by "the bot can reach profile urls". maybe a screen cast or screenshots can help explain?

**Comment by slinkyone** [comment]
> hi. i'm not sure what you mean by "the bot can reach profile urls". maybe a screen cast or screenshots can help explain?

Sure thanks

**Comment by slinkyone** [comment]
Sure: https://imgur.com/a/ExXZDku

**Comment by Luen** [comment]
This sometimes happens for me also. It might be that Instagram is blocking it by returning a 404? Useragent? Login session? Not sure. 
I can do a video recording if it, if that's helpful.

**Comment by slinkyone** [comment]
Any other browser or another chrome tab works flawlessly. Just the bot emulated one returns this error.

**Comment by slinkyone** [comment]
> This sometimes happens for me also. It might be that Instagram is blocking it by returning a 404? Useragent? Login session? Not sure.
> I can do a video recording if it, if that's helpful.

How long does it takes to work again for you?

**Comment by slinkyone** [comment]
Its literally unusable since then.

**Comment by mifi** [comment]
seems like it's the same issue as this: https://github.com/mifi/SimpleInstaBot/issues/142

**Comment by slinkyone** [comment]
> seems like it's the same issue as this: [mifi/SimpleInstaBot#142](https://github.com/mifi/SimpleInstaBot/issues/142)

Any suggestion? That thread is also unsolved.

**Comment by Luen** [comment]
Wait for a few days (or weeks) and try again with the setting set very low.

**Comment by Flamintus** [comment]
Hello, I Am very happy to find this thread cause it's also happened to me. Here is what I can say about this issue.
- Happend using only the unfollowNonMutualFollowers method with dontUnfollowUntilTimeElapsed: 30 * 24 * 60 * 60 * 1000 (30 days) and maxFollowsPerDay: 120, maxFollowsPerHour: 8
- I get this error from Instauto : Failed to check if user follows us TimeoutError: Timeout exceeded while waiting for event
    at Timeout.<anonymous (C:\Users\User\Desktop\Instauto\node_modules\puppeteer\lib\cjs\puppeteer\common\util.js:138:28)
- Getting the url from my browser give me the error (Page unaviailable) AND Some : Failed to load resource: the server responded with a status of 429 on many URI
- Status 429 mean TO MANY REQUEST so it's like a baned state
- Max Unfolowed user before be baned : 97

**Comment by mifi** [comment]
@Flamintus for TimeoutError, see #115

**Comment by Flamintus** [comment]
@mifi For information : I've fixed the issue by reducing max follow par hour and ped day to 5 and 50 it have been working for 500 unfollow. 
I have also update as seen in #115 
i have increased to 7 and 100, Will see if it work, I let you know

PS : In the last version I get this kind of information using unfollow non mutual users method, is it normal ?

2022-08-04T11:44:05.194Z Need to intercept network request to get user data
2022-08-04T11:44:10.208Z Unable to intercept request, will send manually

**Comment by mifi** [comment]
normal.

**Comment by Flamintus** [comment]
> 

Ok thanks for the confirmation.

Unfortunately today, the same think happened 👎 

`2022-08-05T09:09:30.490Z Have now unfollowed (or tried to unfollow) 115 users
2022-08-05T09:09:30.491Z Have reached daily follow/unfollow limit, waiting 10 min
2022-08-05T09:09:30.491Z Waiting 1059.37 sec
2022-08-05T09:27:09.870Z Checking if user marcos_vinicios__75 follows us
2022-08-05T09:27:09.870Z Trying to get user data from HTML
2022-08-05T09:27:09.870Z Navigating to user marcos_vinicios__75
2022-08-05T09:27:09.870Z Goto https://www.instagram.com/marcos_vinicios__75
2022-08-05T09:27:13.978Z Page loaded
2022-08-05T09:27:13.978Z Waiting 2.64 sec
2022-08-05T09:27:16.641Z Need to intercept network request to get user data
2022-08-05T09:27:21.647Z Unable to intercept request, will send manually
2022-08-05T09:27:21.798Z Failed to manually send request Error: Evaluation failed: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\User\Desktop\Instauto\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\User\Desktop\Instauto\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
    at async Timeout._onTimeout (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:294:11)
2022-08-05T09:27:21.800Z Failed to check if user follows us SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at getUserDataFromInterceptedRequest (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:315:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async navigateToUserAndGetData (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:334:16)
    at async doesUserFollowMe (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:1060:30)
    at async condition (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:1104:25)
    at async safelyUnfollowUserList (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:803:13)
    at async C:\Users\User\Desktop\Instauto\followlikers.js:112:5
2022-08-05T09:27:21.801Z User follows us? undefined
2022-08-05T09:27:21.801Z Checking if user henry_m239 follows us
2022-08-05T09:27:21.801Z Trying to get user data from HTML
2022-08-05T09:27:21.803Z Navigating to user henry_m239
2022-08-05T09:27:21.803Z Goto https://www.instagram.com/henry_m239
2022-08-05T09:27:24.845Z Page loaded
2022-08-05T09:27:24.845Z Waiting 2.22 sec
2022-08-05T09:27:27.082Z Cannot find text "henry_m239" on page
2022-08-05T09:27:27.082Z Failed to check if user follows us Error: User not found
    at navigateToUserWithCheck (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:245:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async navigateToUserAndGetData (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:324:5)
    at async doesUserFollowMe (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:1060:30)
    at async condition (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:1104:25)
    at async safelyUnfollowUserList (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:803:13)
    at async C:\Users\User\Desktop\Instauto\followlikers.js:112:5
2022-08-05T09:27:27.083Z User follows us? undefined
2022-08-05T09:27:27.083Z Checking if user b.bright_48 follows us
2022-08-05T09:27:27.083Z Trying to get user data from HTML
2022-08-05T09:27:27.083Z Navigating to user b.bright_48
2022-08-05T09:27:27.083Z Goto https://www.instagram.com/b.bright_48
2022-08-05T09:27:29.840Z Page loaded
2022-08-05T09:27:29.840Z Waiting 3.00 sec
2022-08-05T09:27:32.848Z Cannot find text "b.bright_48" on page
2022-08-05T09:27:32.848Z Failed to check if user follows us Error: User not found
    at navigateToUserWithCheck (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:245:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async navigateToUserAndGetData (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:324:5)
    at async doesUserFollowMe (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:1060:30)
    at async condition (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:1104:25)
    at async safelyUnfollowUserList (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:803:13)
    at async C:\Users\User\Desktop\Instauto\followlikers.js:112:5
2022-08-05T09:27:32.848Z User follows us? undefined
2022-08-05T09:27:32.848Z Checking if user bobo_drik follows us
2022-08-05T09:27:32.848Z Trying to get user data from HTML
2022-08-05T09:27:32.848Z Navigating to user bobo_drik
2022-08-05T09:27:32.848Z Goto https://www.instagram.com/bobo_drik
2022-08-05T09:27:36.383Z Page loaded
2022-08-05T09:27:36.383Z Waiting 2.75 sec
2022-08-05T09:27:39.145Z Cannot find text "bobo_drik" on page
2022-08-05T09:27:39.145Z Failed to check if user follows us Error: User not found
    at navigateToUserWithCheck (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:245:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async navigateToUserAndGetData (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:324:5)
    at async doesUserFollowMe (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:1060:30)
    at async condition (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:1104:25)
    at async safelyUnfollowUserList (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:803:13)
    at async C:\Users\User\Desktop\Instauto\followlikers.js:112:5`


![image](https://user-images.githubusercontent.com/3715133/183080624-45142ca6-366b-439d-a025-c470e30a7914.png)
