### ISSUE TITLE
Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by ali35351** [mifi/instauto#123]
when i start instauto after a few seconds i got this error:
```
2022-08-23T11:14:04.834Z Failed to set language, trying fallback (cookie) TimeoutError: Navigation timeout of 30000 ms exceeded
    at LifecycleWatcher._LifecycleWatcher_createTimeoutPromise (C:\Users\ALi\Downloads\instauto\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:164:12)
TimeoutError: Navigation timeout of 30000 ms exceeded
    at LifecycleWatcher._LifecycleWatcher_createTimeoutPromise (C:\Users\ALi\Downloads\instauto\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:164:12)
Closing browser
```
can someone help me?

**Comment by mifi** [comment]
pleae provide the requested info
