### ISSUE TITLE
Failed to get user data from page

### ISSUE THREAD

**Issue by Flamintus** [mifi/instauto#124]
Here is a new error I encounter, I think about se same "softban" from IG as #112

2022-08-31T05:54:26.085Z Trying to get user data from HTML
2022-08-31T05:54:26.085Z Navigating to user eduardo_frn
2022-08-31T05:54:26.085Z Goto https://www.instagram.com/eduardo_frn
2022-08-31T05:54:31.791Z Page loaded
2022-08-31T05:54:31.791Z Waiting 3.21 sec
2022-08-31T05:54:35.036Z Failed to get user data from page SyntaxError: Unexpected token O in JSON at position 72189
    at JSON.parse (<anonymous>)
    at getUserDataFromPage (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:277:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async navigateToUserAndGetData (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:325:20)
    at async doesUserFollowMe (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:1060:30)
    at async condition (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:1104:25)
    at async safelyUnfollowUserList (C:\Users\User\Desktop\Instauto\node_modules\instauto\src\index.js:803:13)

**Comment by mifi** [comment]
Any chance you could get the html from the page or a screenshot?

**Comment by Flamintus** [comment]
I will try 
I can say at this time that le letter is changing
2022-08-31T11:30:08.515Z Failed to get user data from page SyntaxError: Unexpected token L in JSON at position 26195
2022-08-31T11:30:36.113Z Failed to get user data from page SyntaxError: Unexpected token e in JSON at position 12938
2022-08-31T11:30:36.113Z Failed to get user data from page SyntaxError: Unexpected token e in JSON at position 12938
2022-08-31T11:33:48.377Z Failed to get user data from page SyntaxError: Unexpected token C in JSON at position 24289

Also, it randomly happened till the time where it happen everytime

**Comment by Flamintus** [comment]
Here is a screenshot (I am unable to get the follower list)

![image](https://user-images.githubusercontent.com/3715133/187679411-b3b81ba9-9dc3-44d9-ae12-f2275c05b6c6.png)

**Comment by mifi** [comment]
Oh yea, maybe we need to have a global event that gets triggered and handled if any request fails with 429
