### ISSUE TITLE
Cant load follower info / cant unfollow users

### ISSUE THREAD

**Issue by slinkyone** [mifi/instauto#127]
**To Reproduce**
run the js with node st command.

it breaks at line 100:  await instauto.unfollowNonMutualFollowers();

2022-10-04T08:34:29.926Z User follows us? undefined
2022-10-04T08:34:29.927Z Checking if user pusztai14 follows us
2022-10-04T08:34:29.927Z Trying to get user data from HTML
2022-10-04T08:34:29.927Z Navigating to user pusztai14
2022-10-04T08:34:29.927Z Goto https://www.instagram.com/pusztai14
2022-10-04T08:34:29.928Z Failed to check if user follows us Error: Protocol error (Page.navigate): Session closed. Most likely the page has been closed.
    at CDPSessionImpl.send (C:\Users\m\Desktop\instapy-quickstart-master\instauto\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:316:35)
    at navigate (C:\Users\m\Desktop\instapy-quickstart-master\instauto\node_modules\puppeteer\lib\cjs\puppeteer\common\Frame.js:228:47)
    at Frame.goto (C:\Users\m\Desktop\instapy-quickstart-master\instauto\node_modules\puppeteer\lib\cjs\puppeteer\common\Frame.js:206:13)
    at CDPPage.goto (C:\Users\m\Desktop\instapy-quickstart-master\instauto\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1083:91)
    at gotoUrl (C:\Users\m\Desktop\instapy-quickstart-master\instauto\node_modules\instauto\src\index.js:184:39)
    at gotoWithRetry (C:\Users\m\Desktop\instapy-quickstart-master\instauto\node_modules\instauto\src\index.js:190:30)
    at navigateToUser (C:\Users\m\Desktop\instapy-quickstart-master\instauto\node_modules\instauto\src\index.js:224:26)
    at navigateToUserWithCheck (C:\Users\m\Desktop\instapy-quickstart-master\instauto\node_modules\instauto\src\index.js:246:17)
    at navigateToUserAndGetData (C:\Users\mDesktop\instapy-quickstart-master\instauto\node_modules\instauto\src\index.js:325:11)
    at doesUserFollowMe (C:\Users\m\Desktop\instapy-quickstart-master\instauto\node_modules\instauto\src\index.js:1091:36)
2022-10-04T08:34:29.930Z User follows us? undefined
Error: Protocol error (Page.navigate): Session closed. Most likely the page has been closed.
    at CDPSessionImpl.send (C:\Users\m\Desktop\instapy-quickstart-master\instauto\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:316:35)
    at navigate (C:\Users\m\Desktop\instapy-quickstart-master\instauto\node_modules\puppeteer\lib\cjs\puppeteer\common\Frame.js:228:47)
    at Frame.goto (C:\Users\m\Desktop\instapy-quickstart-master\instauto\node_modules\puppeteer\lib\cjs\puppeteer\common\Frame.js:206:13)
    at CDPPage.goto (C:\Users\m\Desktop\instapy-quickstart-master\instauto\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1083:91)
    at graphqlQueryUsers (C:\Users\m\Desktop\instapy-quickstart-master\instauto\node_modules\instauto\src\index.js:521:18)
    at graphqlQueryUsers.next (<anonymous>)
    at safelyUnfollowUserList (C:\Users\m\Desktop\instapy-quickstart-master\instauto\node_modules\instauto\src\index.js:829:22)
    at async C:\Users\m\Desktop\instapy-quickstart-master\instauto\st.js:100:5

**Comment by mifi** [comment]
was the page closed? or what did you see on the page?
