### ISSUE TITLE
Error: User not found

### ISSUE THREAD

**Issue by Mxrksy** [mifi/instauto#138]
Upon Authentication and Navigating to Profile Page the following error is received

Was running perfectly fine - then I kept getting this error on user profiles am I shadow banned on Instagram - profiles load fine when accessing via mobile etc.

https://ibb.co/nQDfwsK

```
2023-01-10T12:36:01.209Z Cannot find text "***" on page
Error: User not found
    at navigateToUserWithCheck (/home/kali/instagrtam/instauto/node_modules/instauto/src/index.js:248:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async navigateToUserAndGetData (/home/kali/instagrtam/instauto/node_modules/instauto/src/index.js:327:5)                                                                                                             
    at async Instauto (/home/kali/instagrtam/instauto/node_modules/instauto/src/index.js:1090:28)
    at async /home/kali/instagrtam/instauto/example2.js:94:22
Closing browser

```

**Comment by mifi** [comment]
duplicate of #112
