### ISSUE TITLE
 Follow button not found

### ISSUE THREAD

**Issue by pedroldi** [mifi/instauto#144]
Hi there,

I'm writing to report an error that I encountered while using Instauto. Specifically, I received the following error message:

"Failed to process follower masa.rs14 Error: Follow button not found
at followUser (C:\Users\Usuario\node_modules\instauto\src\index.js:437:13)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async followUserRespectingRestrictions (C:\Users\Usuario\node_modules\instauto\src\index.js:751:5)
at async processUserFollowers (C:\Users\Usuario\node_modules\instauto\src\index.js:786:49)
at async Object.processUsersFollowers [as followUsersFollowers] (C:\Users\Usuario\node_modules\instauto\src\index.js:817:9)
at async C:\Users\Usuario\Desktop\Instabot note.js\instauto-master\example.js:122:5
2023-04-29T14:28:10.476Z Waiting 36.72 sec"

It appears that the application is unable to locate the "Follow" button on Instagram. I have checked to ensure that the button is present and have also verified that the account I am attempting to follow has not been blocked or restricted.

Could you please provide guidance on how to resolve this error?

Thank you for your help!

**Comment by mifi** [comment]
If you can provide the html that would be useful

**Comment by pedroldi** [comment]
Sorry, the error occurs in the instagram profiles html when you try to follow them

2023-04-29T17:27:57.248Z Trying to get user data from HTML
2023-04-29T17:27:57.248Z Navigating to user bsjsjbsjskmwksb
2023-04-29T17:27:57.248Z Goto https://www.instagram.com/bsjsjbsjskmwksb
2023-04-29T17:28:02.204Z Page loaded
2023-04-29T17:28:02.204Z Waiting 2.26 sec
2023-04-29T17:28:04.512Z Need to intercept network request to get user data
2023-04-29T17:28:09.520Z Unable to intercept request, will send manually
2023-04-29T17:28:09.920Z Failed to process follower bsjsjbsjskmwksb Error: Follow button not found
    at followUser (C:\Users\Usuario\node_modules\instauto\src\index.js:437:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async followUserRespectingRestrictions (C:\Users\Usuario\node_modules\instauto\src\index.js:751:5)
    at async processUserFollowers (C:\Users\Usuario\node_modules\instauto\src\index.js:786:49)
    at async Object.processUsersFollowers [as followUsersFollowers] (C:\Users\Usuario\node_modules\instauto\src\index.js:817:9)
    at async C:\Users\Usuario\Desktop\Instabot note.js\instauto-master\example.js:122:5
2023-04-29T17:28:09.923Z Waiting 31.97 sec
