### ISSUE TITLE
Like button section not found

### ISSUE THREAD

**Issue by selique** [mifi/instauto#30]
Failed to follow user's images solwinkler_ Error: Evaluation failed: Error: Like button section not found
    at likeCurrentUserImagesPageCode (__puppeteer_evaluation_script__:38:27)
    at ExecutionContext._evaluateInternal (/opt/bitnami/projects/instauto/node_modules/puppeteer/lib/cjs/puppeteer/common/Execut
ionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/opt/bitnami/projects/instauto/node_modules/puppeteer/lib/cjs/puppeteer/common/Execution
Context.js:106:16)
    at async likeCurrentUserImages (/opt/bitnami/projects/instauto/node_modules/instauto/index.js:439:5)
    at async followUserFollowers (/opt/bitnami/projects/instauto/node_modules/instauto/index.js:509:15)
    at async Object.followUsersFollowers (/opt/bitnami/projects/instauto/node_modules/instauto/index.js:538:9)
    at async /opt/bitnami/projects/instauto/example.js:65:5

**Comment by mifi** [comment]
I'm not sure what's happening here, it seems to only happen sometimes, and I cannot reproduce it.

**Comment by mifi** [comment]
I added code that takes screenshot when this error occurs. enable it with the option `screenshotOnError: true`

**Comment by mifi** [comment]
![1601150049450](https://user-images.githubusercontent.com/402547/94362350-f50b2f00-00ba-11eb-8cbc-7a9d863af4c8.jpg)


After taking a screenshot upon the error, I got this. So it seems to be caused by some kind of throttling from instagram's side.

**Comment by sinaukode** [comment]
if something happens like that, what I do is delete cookies and restart the service,
or is there something else?

**Comment by selique** [comment]
i try restart but i thouth the chante elements or id from DOM
