### ISSUE TITLE
undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by makafui294** [mifi/instauto#47]
first of all a big thumbs up to this repository. It has been very helpful in automating our instagram feeds and pages however i'm experiencing this error every time i start the bot. 

undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at shuffleArray (/Users/eggseed-Naaman/Desktop/eggseedapp/backend/api/automation-bot/node_modules/instauto/index.js:11:17)
    at Object.followUsersFollowers (/Users/eggseed-Naaman/Desktop/eggseedapp/backend/api/automation-bot/node_modules/instauto/index.js:567:44)
    at /Users/eggseed-Naaman/Desktop/eggseedapp/backend/api/automation-bot/src/bot.js:52:24

Has anyone faced this problem and if so what can be done to solve it. 

i checked the shuffleArray function and it returns the array but for some reason it returns undefined.

**Comment by mifi** [comment]
Please procide some code to reproduce the issue
