### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rjworks** [mifi/instauto#60]
```
Failed to unfollow, continuing with next Error: Navigate to user returned status 560
at navigateToUser (/home/pogi/instauto/node_modules/instauto/index.js:182:11)
at async safelyUnfollowUserList (/home/pogi/instauto/node_modules/instauto/index.js:594:27)
at async Object.unfollowNonMutualFollowers (/home/pogi/instauto/node_modules/instauto/index.js:657:5)
at async /home/pogi/instauto/example.js:68:6
```

**Comment by mifi** [comment]
please provide more info. how can you reproduce the issue?

**Comment by rjworks** [comment]
i just started the program and this happened while unfollowing a certain user

**Comment by mifi** [comment]
Does it happen again or just once ever?

**Comment by mifi** [comment]
I think this has been fixed because we retry on 560 now.
