### ISSUE TITLE
SyntaxError: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by doge0007** [mifi/instauto#90]
Hello, I have recently started using instaauto to manage my instagram networks and this error has started to appear and the window closes. I would appreciate your help.

SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at getPageJson (D:\iNSTAbOT\node_modules\instauto\index.js:220:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async navigateToUserAndGetData (D:\iNSTAbOT\node_modules\instauto\index.js:231:20)
    at async Instauto (D:\iNSTAbOT\node_modules\instauto\index.js:937:22)
    at async D:\iNSTAbOT\node_modules\instauto\example.js:69:22
Closing browser

**Comment by doge0007** [comment]
I have logged in through the normal google chrome browser and when checking in the developer tools it is telling me to implement the following to solve this error:

A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.

@mifi  , how would this be implemented?

**Comment by mifi** [comment]
maybe you can try to see what is showing in the page. also does it happen on all accounts?

**Comment by mifi** [comment]
looks like the same issue as https://github.com/mifi/SimpleInstaBot/issues/125

**Comment by doge0007** [comment]
@mifi  It happens to me only in this account that has started to stop following. I have also tried with the simpleinstabot app and without result.

**Comment by mifi** [comment]
this should now be fixed
